# Required metadata
sonar.projectKey=attendance-analytics-dashboard
sonar.organization=Sarvagya2003jn

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Paths to source directories 
sonar.sources=src
sonar.tests=tests

# Exclude test files from code coverage/duplication checks
sonar.exclusions=tests/**, dist/**
